events {} # Mandatory structural block
error_log /var/log/nginx/error.log notice; # or warn/error/info

http {
    include /etc/nginx/mime.types; # good to add with wordpress

    access_log /var/log/nginx/access.log;
    
    server {
        listen 443 ssl;
        # server_name ahaddadi.1337.ma;# $DOMAIN_NAME
        server_name glorious-space-waddle-qx7v5j4j5xp269pp-443.app.github.dev;

        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;
        ssl_protocols TLSv1.2 TLSv1.3;

        # wordpres magic
        root /var/www/html;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_pass wordpress:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            # fastcgi_param HTTP_HOST $host;
        }
    }
}