version: '3.8'

services:
  mariadb:
    build:
      context: ./maria
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: on-failure
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - maria_normal
      - maria_root

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # change this 
      device: /workspaces/codespaces-blank/data/maria

secrets:
  maria_normal:
    file: ../secrets/maria_normal
  maria_root:
    file: ../secrets/maria_root